---
coverage:
  status:
    project: false
    patch: off

ignore:
  - "docs/**/*"
  - "tests/**/*"
  - "internal/utils/testutils/*"
  - "lib/openvpn-auth-oauth2/*.go"
  - "lib/openvpn-auth-oauth2/c/*"
  - "lib/openvpn-auth-oauth2/log/*"
  - "pkg/**/*"
  - "wiki/**/*"
