linters:
  enable-all: true
  disable:
    - deadcode
    - scopelint
    - exhaustivestruct
    - structcheck
    - interfacer
    - maligned
    - golint
    - nosnakecase
    - ifshort
    - varcheck
    - depguard
    - exhaustruct
    - gomnd
    - dupl
    - forbidigo
    - funlen
    - ireturn
    - goerr113
    - gomoddirectives

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
        - gocognit
        - cyclop
        - wrapcheck
        - maintidx
        - dogsled
        - contextcheck
        - dupword

linters-settings:
  varnamelen:
    ignore-names:
      - tt
    ignore-decls:
      - i int
      - a ...any
      - err error
      - ok bool
      - id string
      - w http.ResponseWriter
      - rt http.RoundTripper
      - r *http.Request
      - l net.Listener
      - t reflect.Type
      - wg sync.WaitGroup
      - k *koanf.Koanf
      - mu sync.Mutex
      - ts oauth2.TokenSource
  lll:
    line-length: 160
