linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - funlen
    - ireturn
    - err113
    - mnd
    - exportloopref
    - recvcheck # https://github.com/raeperd/recvcheck/issues/7

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - lll
        - gocognit
        - cyclop
        - wrapcheck
        - maintidx
        - dogsled
        - contextcheck
        - dupword
        - dupl
        - funlen
        - gocyclo

linters-settings:
  gosec:
    excludes:
      - G101 # Potential hardcoded credentials
  sloglint:
    no-mixed-args: true
    kv-only: false
    attr-only: true
    no-global: "all"
    context: "scope"
    static-msg: false
    no-raw-keys: false
    key-naming-case: snake
    forbidden-keys:
      - time
      - level
      - msg
      - source
    args-on-sep-lines: true
  varnamelen:
    ignore-names:
      - tt
    ignore-decls:
      - i int
      - a ...any
      - err error
      - ok bool
      - id string
      - w http.ResponseWriter
      - rt http.RoundTripper
      - r *http.Request
      - l net.Listener
      - t reflect.Type
      - wg sync.WaitGroup
      - k *koanf.Koanf
      - mu sync.Mutex
      - ts oauth2.TokenSource
      - ca *testcerts.CertificateAuthority
  lll:
    line-length: 160
