version: 2
before:
  hooks:
    - rm -rf 3rdpartylicenses
    - go run github.com/google/go-licenses@latest save . --save_path=3rdpartylicenses

builds:
  - id: "openvpn-auth-oauth2"
    binary: openvpn-auth-oauth2
    goos:
      - linux
      - freebsd
      - openbsd
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - >-
        -s -w
        -X internal/version.Version={{.Version}}
        -X internal/version.Commit={{.Commit}}
        -X internal/version.Date={{.Date}}

archives:
  - id: openvpn-auth-oauth2
    ids:
        - openvpn-auth-oauth2
    formats: ['tar.xz']
    files:
        - LICENSE.txt
        - 3rdpartylicenses/**/*

nfpms:
  - id: openvpn-auth-oauth2
    ids:
      - openvpn-auth-oauth2
    homepage: https://github.com/jkroepke/openvpn-auth-oauth2
    maintainer: Jan-Otto Kröpke <github@jkroepke.de>
    section: net
    description: |
      openvpn-auth-oauth2 is a management client for OpenVPN that handles the authentication of connecting users against OIDC providers like Azure AD or Keycloak.
    license: MIT License
    formats:
      - deb
      - rpm
    provides:
      - openvpn-auth-oauth2
    recommends:
      - openvpn
    contents:
      - src: packaging/usr/lib/sysusers.d/
        dst: /usr/lib/sysusers.d/
      - src: packaging/usr/lib/systemd/system/
        dst: /usr/lib/systemd/system/
      - src: packaging/etc/apparmor.d/
        dst: /etc/apparmor.d/
      - src: packaging/etc/sysconfig/openvpn-auth-oauth2
        file_info:
          mode: 0640
        dst: /etc/sysconfig/openvpn-auth-oauth2
        type: "config|noreplace"
      - dst: /etc/openvpn-auth-oauth2/
        type: dir
        file_info:
          owner: root
          group: openvpn-auth-oauth2
          mode: 0750
      - dst: /etc/openvpn-auth-oauth2/client-config/
        type: dir
        file_info:
          owner: root
          group: openvpn-auth-oauth2
          mode: 0750
      - src: packaging/etc/openvpn-auth-oauth2/config.yaml
        dst: /etc/openvpn-auth-oauth2/config.yaml
        type: "config|noreplace"
        file_info:
          owner: root
          group: openvpn-auth-oauth2
          mode: 0640
      - src: 3rdpartylicenses/
        dst: /usr/share/doc/openvpn-auth-oauth2/3rdpartylicenses/
        type: tree
        file_info:
          owner: root
          group: root
          mode: 0644
    scripts:
      preinstall: "packaging/scripts/preinst.sh"
      postinstall: "packaging/scripts/postinst.sh"
      preremove: "packaging/scripts/preremove.sh"
      postremove: "packaging/scripts/postremove.sh"
    rpm:
      compression: xz
      signature:
        key_file: "{{ .Env.GPG_KEY_PATH }}"
    deb:
      #compression: xz
      signature:
        key_file: "{{ .Env.GPG_KEY_PATH }}"


report_sizes: true

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

gomod:
  proxy: true

release:
  prerelease: auto

changelog:
  use: github-native
