builds:
  - id: "openvpn-auth-oauth2"
    binary: openvpn-auth-oauth2
    buildmode: pie
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Arch "amd64"}}CC=x86_64-linux-gnu-gcc{{- end }}
        {{- if eq .Arch "arm64"}}CC=aarch64-linux-gnu-gcc{{- end }}
      - >-
        {{- if eq .Arch "amd64"}}CXX=x86_64-linux-gnu-g++{{- end }}
        {{- if eq .Arch "arm64"}}CXX=aarch64-linux-gnu-g++{{- end }}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    tags:
      - osusergo
      - netgo
      - static_build
    flags:
      - -trimpath
    ldflags:
      # https://github.com/golang/go/issues/41944#issuecomment-711025202
      - -linkmode external -extldflags "--static-pie"
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser
  - id: "openvpn-auth-oauth2.so"
    binary: openvpn-auth-oauth2
    main: ./pkg/plugin/
    buildmode: c-shared
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Arch "amd64"}}CC=x86_64-linux-gnu-gcc{{- end }}
        {{- if eq .Arch "arm64"}}CC=aarch64-linux-gnu-gcc{{- end }}
      - >-
        {{- if eq .Arch "amd64"}}CXX=x86_64-linux-gnu-g++{{- end }}
        {{- if eq .Arch "arm64"}}CXX=aarch64-linux-gnu-g++{{- end }}

archives:
  - id: openvpn-auth-oauth2
    builds:
        - openvpn-auth-oauth2
    format: tar.xz
    files:
        - LICENSE.txt
        - 3rdpartylicenses/**/*

nfpms:
  - id: openvpn-auth-oauth2
    builds:
      - openvpn-auth-oauth2
    homepage: https://github.com/jkroepke/openvpn-auth-oauth2
    maintainer: Jan-Otto Kröpke <github@jkroepke.de>
    section: net
    description: |
      openvpn-auth-oauth2 is a management client for OpenVPN that handles the authentication of connecting users against OIDC providers like Azure AD or Keycloak.
    license: MIT License
    formats:
      - deb
      - rpm
    provides:
      - openvpn-auth-oauth2
    recommends:
      - openvpn
    contents:
      - src: packaging/usr/lib/sysusers.d/
        dst: /usr/lib/sysusers.d/
      - src: packaging/usr/lib/systemd/system/
        dst: /usr/lib/systemd/system/
      - src: packaging/etc/sysconfig/openvpn-auth-oauth2
        file_info:
          mode: 0640
        dst: /etc/sysconfig/openvpn-auth-oauth2
        type: "config|noreplace"
      - dst: /etc/openvpn-auth-oauth2/
        type: dir
        file_info:
          owner: root
          group: openvpn-auth-oauth2
          mode: 0750
      - src: packaging/etc/openvpn-auth-oauth2/config.yaml
        dst: /etc/openvpn-auth-oauth2/config.yaml
        type: "config|noreplace"
        file_info:
          owner: root
          group: openvpn-auth-oauth2
          mode: 0640
      - src: 3rdpartylicenses/
        dst: /usr/share/doc/openvpn-auth-oauth2/3rdpartylicenses/
        type: tree
        file_info:
          owner: root
          group: root
          mode: 0644
    scripts:
      preinstall: "packaging/scripts/postinst.sh"
      postinstall: "packaging/scripts/postinst.sh"
      preremove: "packaging/scripts/preremove.sh"
      postremove: "packaging/scripts/postremove.sh"
    rpm:
      compression: xz
      signature:
        key_file: "{{ .Env.GPG_KEY_PATH }}"
    deb:
      #compression: xz
      signature:
        key_file: "{{ .Env.GPG_KEY_PATH }}"


report_sizes: true

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

gomod:
  proxy: true

release:
  prerelease: auto

changelog:
  use: github-native
