builds:
  - id: "openvpn-auth-oauth2"
    binary: openvpn-auth-oauth2
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
  - id: "openvpn-auth-oauth2.so"
    binary: openvpn-auth-oauth2
    main: ./plugin/
    buildmode: c-shared
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    mod_timestamp: '{{ .CommitTimestamp }}'

archives:
  - id: openvpn-auth-oauth2
    allow_different_binary_count: true

nfpms:
  - id: openvpn-auth-oauth2
    homepage: https://github.com/jkroepke/openvpn-auth-oauth2
    maintainer: Jan-Otto Kröpke <github@jkroepke.de>
    description: |
      openvpn-auth-oauth2 is a management client for OpenVPN that handles the authentication of connecting users against OIDC providers like Azure AD or Keycloak.
    license: MIT License
    builds:
      - openvpn-auth-oauth2
    formats:
      - deb
      - rpm
    contents:
      - src: packaging/openvpn-auth-oauth2.service
        dst: /usr/lib/systemd/system/openvpn-auth-oauth2.service
      - src: packaging/openvpn-auth-oauth2.sysconfig
        dst: /etc/sysconfig/openvpn-auth-oauth2
        type: "config|noreplace"

release:
  prerelease: auto

changelog:
  use: github-native
