builds:
  - id: "openvpn-auth-oauth2"
    binary: openvpn-auth-oauth2
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
  - id: "openvpn-auth-oauth2.so"
    binary: openvpn-auth-oauth2
    main: ./lib/plugin/
    buildmode: c-shared
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Arch "amd64"}}CC=x86_64-linux-gnu-gcc{{- end }}
        {{- if eq .Arch "arm64"}}CC=aarch64-linux-gnu-gcc{{- end }}
      - >-
        {{- if eq .Arch "amd64"}}CXX=x86_64-linux-gnu-g++{{- end }}
        {{- if eq .Arch "arm64"}}CXX=aarch64-linux-gnu-g++{{- end }}

archives:
  - id: openvpn-auth-oauth2

nfpms:
  - id: openvpn-auth-oauth2
    homepage: https://github.com/jkroepke/openvpn-auth-oauth2
    maintainer: Jan-Otto Kröpke <github@jkroepke.de>
    description: |
      openvpn-auth-oauth2 is a management client for OpenVPN that handles the authentication of connecting users against OIDC providers like Azure AD or Keycloak.
    license: MIT License
    formats:
      - deb
      - rpm
    contents:
      - src: packaging/openvpn-auth-oauth2.service
        dst: /usr/lib/systemd/system/openvpn-auth-oauth2.service
      - src: packaging/openvpn-auth-oauth2.sysconfig
        dst: /etc/sysconfig/openvpn-auth-oauth2
        type: "config|noreplace"
      - src: packaging/config.yaml
        dst: /usr/share/doc/openvpn-auth-oauth2/examples/auth-oauth2.yaml

report_sizes: true

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

gomod:
  proxy: true

release:
  prerelease: auto

changelog:
  use: github-native
