builds:
  - binary: openvpn-auth-oauth2
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    no_unique_dist_dir: true
