#debug:
#    pprof: false
#    listen: :9001
#http:
#    baseurl: "http://localhost:9000/"
#    cert: ""
#    check:
#        ipaddr: false
#    enable-proxy-headers: true
#    key: ""
#    listen: ":9000"
#    secret: ""
#    template: "" # Path to a HTML file which is displayed at the end of the screen
#    tls: false
#log:
#    format: console
#    level: INFO
#oauth2:
#    authorize-params: "a=c"
#    client:
#        id: "test"
#        secret: "test"
#    endpoint:
#        discovery: "https://idp/.well-known/openid-configuration"
#        auth: "https://idp/oauth/auth"
#        token: "https://idp/oauth/token"
#    issuer: "https://idp"
#    scopes:
#        - "openid"
#        - "profile"
#    validate:
#        acr:
#            - "phr"
#            - "phrh"
#        common-name: ""
#        groups:
#            - "test"
#            - "test2"
#        roles:
#            - "test"
#            - "test2"
#        ipaddr: false
#        issuer: true
#    nonce: true
#    pkce: true
#    refresh:
#        enabled: false
#        expires: 8h0m0s
#        # secret: ""
#openvpn:
#    addr: "unix:///run/openvpn/server.sock"
#    auth-token-user: true
#    auth-pending-timeout: 2m
#    bypass:
#        common-names:
#        - "test"
#        - "test2"
#    common-name:
#        environment-variable-name: common_name
#        mode: plain
#    password: ""
#provider:
#    google:
#        admin-email: ""
#        impersonate-account: ""
#        service-account-config: ""