#debug:
#  pprof: false
#  listen: :9001
#http:
#  assets-path: "" # Example: "/etc/openvpn-auth-oauth2/assets/"
#  baseurl: "http://localhost:9000/"
#  cert: ""
#  check:
#    ipaddr: false
#  enable-proxy-headers: true
#  key: ""
#  listen: ":9000"
#  secret: ""
#  template: "" # Path to a HTML file which is displayed at the end of the screen
#  tls: false
#log:
#  format: console
#  level: INFO
#  vpn-client-ip: true
#oauth2:
#  authorize-params: "a=c"
#  client:
#    id: "test"
#    secret: "test"
#  endpoint:
#    discovery: "https://idp/.well-known/openid-configuration"
#    auth: "https://idp/oauth/auth"
#    token: "https://idp/oauth/token"
#  issuer: "https://idp"
#  provider: "generic"
#  scopes:
#    - "openid"
#    - "profile"
#  validate:
#    acr: []
#    #  - "phr"
#    #  - "phrh"
#    common-name: ""
#    common-name-case-sensitive: false
#    groups: []
#    #  - "test"
#    #  - "test2"
#    roles: []
#    #  - "test"
#    #  - "test2"
#    ipaddr: false
#    issuer: true
#  nonce: true
#  pkce: true
#  refresh:
#    enabled: false
#    expires: 8h0m0s
#    # secret: ""
#    use-session-id: false
#    validate-user: true
#openvpn:
#  addr: "unix:///run/openvpn/server.sock"  # This is overridden by /etc/sysconfig/openvpn-auth-oauth2
#  auth-token-user: true
#  auth-pending-timeout: 2m
#  bypass:
#    common-names:
#      - "test"
#      - "test2"
#  common-name:
#    environment-variable-name: common_name
#    mode: plain
#  password: ""
#pass-through:
#  enabled: false
#  address: "unix:///run/openvpn/pass-through.sock"
#  password: ""
#  socket-group: ""
#  socket-mode: 660
